  name: Check iosevka version
  on:
    workflow_dispatch:
    workflow_call:
    
  jobs:
    pkg-version:
      name: Check version
      runs-on: ubuntu-latest
      outputs:
        new: ${{ steps.getversion.outputs.new }}
        old: ${{ steps.getversion.outputs.current }}
      steps:
    
      - id: gettag
        name: Get latest release tag
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ryanoasis/nerd-fonts

      - id: getversion
        name: Get current package version
        run: |
          wget -qO - https://foil-hat-guy.github.io/OPi5Plus-Soft/dists/bookworm/contrib/binary-arm64/Packages > packages
          grep -A 16 'Package: iosevka-doc' packages | grep 'Version' | cut -d ' ' -f 2 > currentversion
          echo "current="$(cat currentversion) >> "$GITHUB_OUTPUT"
          echo "new="$(echo ${{ steps.gettag.outputs.release }} | cut -d 'v' -f 1) >> "$GITHUB_OUTPUT"
          echo "current="$(cat currentversion)
          echo "new="$(echo ${{ steps.gettag.outputs.release }}
    
      - name: There is no new version
        if: ${{ steps.getversion.outputs.new == steps.getversion.outputs.current }}
        run: |
            echo ${{ steps.getversion.outputs.new }}
            echo ${{ steps.getversion.outputs.current }}
            echo 'It is the same version!'

    debug:
      needs: pkg-version
      runs-on: ubuntu-latest
      steps:
      - name: print
        run: |
            echo ${{ needs.pkg-version.outputs.new }}_
            echo ${{ needs.pkg-version.outputs.old }}_
            
    build-new:
      name: Update debian repository
      needs: pkg-version
      if: ${{ needs.pkg-version.outputs.new != needs.pkg-version.outputs.old }}
      uses: foil-hat-guy/OPi5Plus-Soft/.github/workflows/update-iosevka.yml@main
      with:
        version: ${{ needs.pkg-version.outputs.new }}
      secrets: inherit
      
