  name: Check fastfetch version
  on:
    workflow_dispatch:
    
  jobs:
    pkg-version:
      name: Check version
      runs-on: ubuntu-latest
      outputs:
        new: ${{ steps.gettag.outputs.release }}
        old: ${{ steps.getversion.outputs.current }}
      steps:
    
      - id: gettag
        name: Get latest release tag
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: fastfetch-cli/fastfetch

      - id: getversion
        name: Get current package version
        run: |
          wget -qO - https://foil-hat-guy.github.io/OPi5Plus-Soft/dists/bookworm/contrib/binary-arm64/Packages > packages
          grep -A 16 'Package: fastfetch' packages | grep 'Version' | cut -d ' ' -f 2 > currentversion
          echo "current="$(cat currentversion) >> "$GITHUB_OUTPUT"
    
      - name: There is no new version
        if: ${{ steps.gettag.outputs.release == steps.getversion.outputs.current }}
        run: |
            echo ${{ steps.gettag.outputs.release }}
            echo ${{ steps.getversion.outputs.current }}
            echo 'It is the same version!'
      
    build-new:
      name: Update debian repository
      needs: pkg-version
      if: ${{ needs.pkg-version.outputs.new != needs.pkg-version.outputs.old }}
      uses: foil-hat-guy/OPi5Plus-Soft/.github/workflows/update-fastfetch.yml@main
      with:
        version: ${{ needs.pkg-version.outputs.new }}
      secrets: inherit
      
        
        
