name: Fastfetch DEB build
on:
  workflow_dispatch:

jobs:
  Build-deb:
    name: Build fastfetch for arm64 architecture
    runs-on: ubuntu-latest
    steps:
    - id: gettag
      name: Get latest release tag
      uses: pozetroninc/github-action-get-latest-release@master
      with:
          repository: fastfetch-cli/fastfetch
      

    - id: builddeb
      name: Build fastfetch.deb
      uses: uraimo/run-on-arch-action@v2.5.0
      with:
        arch: aarch64
        distro: ubuntu_latest
        setup: |
            mkdir -p "${PWD}/artifacts"
        dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
        install: | 
            apt-get update -y
            apt-get -y install apt-utils
            apt-get -y install cmake git pkg-config rpm
        
        run: |
            git clone --branch ${{ steps.gettag.outputs.release }} --depth 1 'https://github.com/fastfetch-cli/fastfetch.git'
            cd fastfetch
            mkdir -p build
            cd build
            cmake ..
            cmake --build . --target package
            echo '====================='
            ls
            cp ./*.deb "/artifacts/fastfetch-stable.deb"
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: fastfetch.deb
        path: /home/runner/work/aarch64/aarch64/artifacts/fastfetch-stable.deb
    
    - name: Prepare repository root folder
      run: |
          mkdir debian 
          cd debian
          sudo apt-get update -y
          sudo apt-get -y install reprepro
          
    - uses: actions/checkout@v3
      with:
        path: './debian'
        
    - name: Setup debian repository
      run: |
          mkdir conf 
          cd conf
          
          touch distributions
          echo 'Origin: foil-hat-guy.github.io/aarch64' >> distributions
          echo 'Label: foil-hat-guy.github.io/aarch64' >> distributions
          echo 'Codename: bookworm' >> distributions
          echo 'Architectures: aarch64 arm64' >> distributions
          echo 'Components: contrib' >> distributions
          echo 'Description: Repository with some additional for Orangepi 5 plus Armbian Bookworm.' >> distributions
          
          cd ../
          reprepro --basedir . includedeb bookworm /home/runner/work/aarch64/aarch64/artifacts/fastfetch-stable.deb
          
          echo '=============================='
          reprepro --basedir ./ list bookworm
          echo '=============================='
          git status
          echo '=============================='
          git add --all
          git commit -m "generated"
          git push origin
          git push
