name: Fastfetch DEB build
on:
  workflow_dispatch:

jobs:
  Build-deb:
    name: Build fastfetch for arm64 architecture
    runs-on: ubuntu-latest
    steps:
    - id: gettag
      name: Get latest release tag
      uses: pozetroninc/github-action-get-latest-release@master
      with:
          repository: fastfetch-cli/fastfetch
      

    - id: builddeb
      name: Build fastfetch.deb
      uses: uraimo/run-on-arch-action@v2.5.0
      with:
        arch: aarch64
        distro: ubuntu_latest
        setup: |
            mkdir -p "${PWD}/artifacts"
        dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
        install: | 
            apt-get update -y
            apt-get -y install apt-utils
            apt-get -y install cmake git pkg-config rpm
        
        run: |
            git clone --branch ${{ steps.gettag.outputs.release }} --depth 1 'https://github.com/fastfetch-cli/fastfetch.git'
            cd fastfetch
            mkdir -p build
            cd build
            cmake ..
            cmake --build . --target package
            echo '====================='
            ls
    # cp ./*.deb "/artifacts/neovim-stable.deb"
    
    # - name: Upload a Build Artifact
    #  uses: actions/upload-artifact@v3.1.2
    #  with:
    #    name: neovim.deb
    #    path: /home/runner/work/aarch64/aarch64/artifacts/neovim-stable.deb
