name: Fastfetch DEB build
on:
  workflow_dispatch:

jobs:
  Build-deb:
    name: Build fastfetch for arm64 architecture
    runs-on: ubuntu-latest
    steps:
    - name: Install dependenties
      run: |
        sudo apt-get update -y
        sudo apt-get -y install reprepro

    - id: gettag
      name: Get latest release tag
      uses: pozetroninc/github-action-get-latest-release@master
      with:
          repository: fastfetch-cli/fastfetch

    - id: getversion
      name: Get current package version
      run: |
        wget -qO - https://foil-hat-guy.github.io/OPi5Plus-Soft/dists/bookworm/contrib/binary-arm64/Packages > packages
        grep -A 16 'Package: fastfetch' packages | grep 'Version' | cut -d ' ' -f 2 > currentversion
        echo "current="$(cat currentversion) >> "$GITHUB_OUTPUT"
    
    - name: Is there a new version
      if: ${{ steps.gettag.outputs.release == steps.getversion.outputs.current }}
      run: |
          echo ${{ steps.gettag.outputs.release }}
          echo ${{ steps.getversion.outputs.current }}
          echo 'It is the same version!'
    
    - name: Import GPG key for debian
      uses: crazy-max/ghaction-import-gpg@v5
      with:
          gpg_private_key: ${{ secrets.DEBIANREPOSIGNATURE }}
          passphrase: ${{ secrets.PASSPHRASE }}
    
    - id: builddeb
      name: Build fastfetch.deb
      uses: uraimo/run-on-arch-action@v2.5.0
      with:
        arch: aarch64
        distro: ubuntu_latest
        setup: |
            mkdir -p "${PWD}/artifacts"
        dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
        install: | 
            apt-get update -y
            apt-get -y install apt-utils
            apt-get -y install cmake git pkg-config rpm
        
        run: |
            git clone --branch ${{ steps.gettag.outputs.release }} --depth 1 'https://github.com/fastfetch-cli/fastfetch.git'
            cd fastfetch
            mkdir -p build
            cd build
            cmake ..
            cmake --build . --target package
            echo '====================='
            ls
            cp ./*.deb "/artifacts/fastfetch-stable.deb"
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: fastfetch.deb
        path: /home/runner/work/OPi5Plus-Soft/OPi5Plus-Soft/artifacts/fastfetch-stable.deb
    
    - name: Prepare repository root folder
      run: |
          mkdir debian 
          cd debian
          
    - uses: actions/checkout@v3
      with:
        path: './debian'
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Prepare files for debian repository
      run: |
          echo '================='
          gpg --list-secret-keys
          echo '================='
          
          cd ./debian/conf
          
          echo 'Origin: foil-hat-guy.github.io/OPi5Plus-Soft' > distributions
          echo 'Label: foil-hat-guy.github.io/OPi5Plus-Soft' >> distributions
          echo 'Codename: bookworm' >> distributions
          echo 'Architectures: arm64' >> distributions
          echo 'Components: contrib' >> distributions
          echo 'Description: Repository with some additional for Orangepi 5 plus Armbian Bookworm.' >> distributions
          echo 'SignWith: yes' >> distributions
          
          cd ../
          gpg --armor --export dev@foilhatguy.casa > PUBLIC.KEY
          echo '================='
          ls
          echo '================='
          reprepro --basedir . list bookworm
          echo '================='
          reprepro --basedir . remove bookworm fastfetch
          reprepro --basedir . includedeb bookworm /home/runner/work/OPi5Plus-Soft/OPi5Plus-Soft/artifacts/fastfetch-stable.deb

    - name: Update git repository
      uses: EndBug/add-and-commit@v9.1.3
      with:
        cwd: './debian'
        message: 'Nightly update of the repository.'

