# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  neovim-aarch64-build:
    runs-on: ubuntu-latest
    name: Build neovim for arm64 architecture
    steps:
    - uses: uraimo/run-on-arch-action@v2.5.0
      id: runcmd
      with:
        arch: aarch64
        distro: ubuntu_latest
        install: | 
                apt-get update -y 
                apt-get -y install ninja-build gettext cmake unzip curl git
        
        run: |
            git clone --branch master --depth 1 'https://github.com/neovim/neovim.git'
