name: Neovim-stable DEB Build
on:
  workflow_dispatch:

jobs:
  neovim-aarch64-build:
    runs-on: ubuntu-latest
    name: Build neovim for arm64 architecture
    steps:
    - name: Build neovim.deb
      uses: uraimo/run-on-arch-action@v2.5.0
      id: runcmd
      with:
        arch: aarch64
        distro: ubuntu_latest
        setup: |
            mkdir -p "${PWD}/artifacts"
        dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
        install: | 
            apt-get update -y
            apt-get -y install apt-utils
            apt-get -y install ninja-build gettext cmake unzip curl git file debhelper
        
        run: |
            git clone --branch stable --depth 1 'https://github.com/neovim/neovim.git'
            cd ./neovim
            make CMAKE_BUILD_TYPE=Release
            cd build 
            cpack -G DEB
            ls
            cp ./*.deb "/artifacts/neovim-stable.deb"
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: neovim.deb
        path: /home/runner/work/aarch64/aarch64/artifacts/neovim-stable.deb
