name: Nightly repo update
on:
  workflow_dispatch:
  schedule:
  - cron: '0 20 * * *'
  
jobs:
  fastfetch:
    uses: foil-hat-guy/OPi5Plus-Soft/.github/workflows/check-fastfetch.yml@main
    secrets: inherit

  neovim:
    uses: foil-hat-guy/OPi5Plus-Soft/.github/workflows/check-neovim.yml@main
    secrets: inherit

  iosevka:
    uses: foil-hat-guy/OPi5Plus-Soft/.github/workflows/iosevka-neovim.yml@main
    secrets: inherit
      
  update-repo:
    needs: [ neovim, fastfetch, iosevka ]
    uses: foil-hat-guy/OPi5Plus-Soft/.github/workflows/update-debian-repo.yml@main
    secrets: inherit
