name: Nightly repo update
on:
  workflow_dispatch:
  schedule:
  - cron: '0 20 * * *'
  
jobs:
  fastfetch:
    uses: foil-hat-guy/Debian-Extra/.github/workflows/check-fastfetch.yml@main
    secrets: inherit

  neovim:
    uses: foil-hat-guy/Debian-Extra/.github/workflows/check-neovim.yml@main
    secrets: inherit

  iosevka:
    uses: foil-hat-guy/Debian-Extra/.github/workflows/check-iosevka.yml@main
    secrets: inherit

  minichlink:
    uses: foil-hat-guy/Debian-Extra/.github/workflows/check-minichlink.yml@main
    secrets: inherit  
      
  update-repo:
    if: ${{ always() }}
    needs: [ neovim, fastfetch, iosevka, minichlink ]
    uses: foil-hat-guy/Debian-Extra/.github/workflows/update-debian-repo.yml@main
    secrets: inherit
