name: Update all packages
on:
  workflow_dispatch:

jobs:
  fastfetch:
    uses: foil-hat-guy/OPi5Plus-Soft/.github/workflows/check-fastfetch.yml@main
    secrets: inherit

  neovim:
    uses: foil-hat-guy/OPi5Plus-Soft/.github/workflows/check-neovim.yml@main
    secrets: inherit
      
  update-repo:
    needs: [ neovim, fastfetch ]
    uses: foil-hat-guy/OPi5Plus-Soft/.github/workflows/update-debian-repo.yml@main
    secrets: inherit
