name: Remove package
on:
  workflow_dispatch:
    inputs:
      pkg-name:
        required: true
        type: string
        
jobs:
  remove-pkg:
    runs-on: ubuntu-latest
    name: Remove package
    steps:
    - name: Import GPG key for debian
      uses: crazy-max/ghaction-import-gpg@v5
      with:
          gpg_private_key: ${{ secrets.DEBIANREPOSIGNATURE }}
          passphrase: ${{ secrets.PASSPHRASE }}
    
    - name: Prepare repository root folder
      run: |
          sudo apt-get update -y
          sudo apt-get -y install reprepro
          mkdir debian 
          cd debian
    
    - uses: actions/checkout@v3
      with:
        path: './debian'
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Prepare files for debian repository
      run: |
          cd ./debian
          reprepro --basedir . remove bookworm ${{ inputs.pkg-name }}
      
    - name: Update git repository
      uses: EndBug/add-and-commit@v9.1.3
      with:
        cwd: './debian'
        message: 'Automatic update of the repository.'
