name: Update debian repository
on:
  workflow_dispatch:
  workflow_call:

jobs:
  update-repo:
    runs-on: ubuntu-latest
    name: Load packages from cache to repo
    outputs:
      has-new-pkg: ${{ contains( steps.*.outputs.cache-hit, 'true' ) }}
    steps:
    - name: Load new fastfetch.deb
      uses: actions/cache/restore@v3.3.1
      id: fastfetch-cache
      with:
        path: /home/runner/work/OPi5Plus-Soft/OPi5Plus-Soft/artifacts/fastfetch.deb
        key: fastfetch.deb
        
    - name: Load new neovim.deb
      uses: actions/cache/restore@v3.3.1
      id: neovim-cache
      with:
        path: /home/runner/work/OPi5Plus-Soft/OPi5Plus-Soft/artifacts/neovim.deb
        key: neovim.deb    
    
    - name: Import GPG key for debian
      if: contains( steps.*.outputs.cache-hit, 'true' )
      uses: crazy-max/ghaction-import-gpg@v5
      with:
          gpg_private_key: ${{ secrets.DEBIANREPOSIGNATURE }}
          passphrase: ${{ secrets.PASSPHRASE }}
    
    - name: Prepare repository root folder
      if: contains( steps.*.outputs.cache-hit, 'true' )
      run: |
          sudo apt-get update -y
          sudo apt-get -y install reprepro
          ls
          mkdir debian 
          
    - uses: actions/checkout@v3
      if: contains( steps.*.outputs.cache-hit, 'true' )
      with:
        path: './debian'
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Prepare files for debian repository
      if: contains( steps.*.outputs.cache-hit, 'true' )
      run: |
          cd ./debian
          reprepro --basedir . includedeb bookworm /home/runner/work/OPi5Plus-Soft/OPi5Plus-Soft/artifacts/*.deb

    - name: Update git repository
      if: contains( steps.*.outputs.cache-hit, 'true' )
      uses: EndBug/add-and-commit@v9.1.3
      with:
        cwd: './debian'
        message: 'Automatic update of the repository.'
        
    - name: Delete Repository Cache
      if: contains( steps.*.outputs.cache-hit, 'true' )
      uses: TheRealRyGuy/clear-cache-action@master
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
    
  report-update:
    name: Successful update report
    runs-on: ubuntu-latest
    if: always() && needs.update-repo.result == 'success' && needs.update-repo.outputs.has-new-pkg == 'true'
    needs: update-repo
    steps:
    - name: Send notification
      uses: appleboy/telegram-action@v0.1.1
      with:
        token: ${{ secrets.TELEGRAMBOT }}
        to: ${{ secrets.TELEGRAMCHAT }}
        message: Debian repository successfuly updated!
        
  report-fail:
    name: Update fail report
    runs-on: ubuntu-latest
    if: always() && needs.update-repo.result == 'failure' 
    needs: update-repo
    steps:
    - name: Send notification
      uses: appleboy/telegram-action@v0.1.1
      with:
        token: ${{ secrets.TELEGRAMBOT }}
        to: ${{ secrets.TELEGRAMCHAT }}
        message: Debian repository failed to update!
        
  report-nonews:
    name: No updates report
    runs-on: ubuntu-latest
    if: always() && needs.update-repo.result == 'success' && needs.update-repo.outputs.has-new-pkg == 'false'
    needs: update-repo
    steps:
    - name: Send notification
      uses: appleboy/telegram-action@v0.1.1
      with:
        token: ${{ secrets.TELEGRAMBOT }}
        to: ${{ secrets.TELEGRAMCHAT }}
        message: There is no updates today.
