name: Neovim DEB Build
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version to be built'
        default: 'v0.9.0'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  neovim-aarch64-build:
    runs-on: ubuntu-latest
    name: Build neovim for arm64
    steps:
    - name: Build neovim.deb
      uses: uraimo/run-on-arch-action@v2
      id: runcmd
      with:
        arch: aarch64
        distro: ubuntu_latest
        setup: |
            mkdir -p "${PWD}/artifacts"
        dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
        install: | 
            apt-get update -y
            apt-get -y install apt-utils
            apt-get -y install ninja-build gettext cmake unzip curl git file debhelper
        
        run: |
            git clone --branch ${{ inputs.version }} --depth 1 'https://github.com/neovim/neovim.git'
            cd ./neovim
            make CMAKE_BUILD_TYPE=Release
            cd build 
            cpack -G DEB
            cp ./*.deb "/artifacts/neovim.deb"
    
    - name: Save DEB to cache
      uses: actions/cache/save@v4
      with:
        path: /home/runner/work/OPi5Plus-Soft/OPi5Plus-Soft/artifacts/neovim.deb
        key: neovim.deb
          
  report-fail:
    name: Report build fail.
    runs-on: ubuntu-latest
    if: always() && needs.neovim-aarch64-build.result == 'failure'
    needs: neovim-aarch64-build
    steps:
    - name: Send notification
      uses: appleboy/telegram-action@v0.1.1
      with:
        token: ${{ secrets.TELEGRAMBOT }}
        to: ${{ secrets.TELEGRAMCHAT }}
        message: Warning! Neovim build failed!

  report-ok:
    name: Report new version.
    runs-on: ubuntu-latest
    if: always() && needs.neovim-aarch64-build.result == 'success'
    needs: neovim-aarch64-build
    steps:
    - name: Send notification
      uses: appleboy/telegram-action@v0.1.1
      with:
        token: ${{ secrets.TELEGRAMBOT }}
        to: ${{ secrets.TELEGRAMCHAT }}
        message: Good News! A new version ${{ inputs.version }} of Neovim is ready!
