name: Fastfetch DEB build
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version to be built'
        default: '1.12.1'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  Build-deb:
    name: Build fastfetch for arm64 architecture
    runs-on: ubuntu-latest
    steps:
    - name: Import GPG key for debian
      uses: crazy-max/ghaction-import-gpg@v5
      with:
          gpg_private_key: ${{ secrets.DEBIANREPOSIGNATURE }}
          passphrase: ${{ secrets.PASSPHRASE }}
    
    - id: builddeb
      name: Build fastfetch.deb
      uses: uraimo/run-on-arch-action@v2.5.0
      with:
        arch: aarch64
        distro: ubuntu_latest
        setup: |
            mkdir -p "${PWD}/artifacts"
        dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
        install: | 
            apt-get update -y
            apt-get -y install apt-utils
            apt-get -y install cmake git pkg-config rpm
        
        run: |
            git clone --branch ${{ inputs.version }} --depth 1 'https://github.com/fastfetch-cli/fastfetch.git'
            cd fastfetch
            mkdir -p build
            cd build
            cmake ..
            cmake --build . --target package
            echo '====================='
            ls
            cp ./*.deb "/artifacts/fastfetch-stable.deb"
    
    - name: Prepare repository root folder
      run: |
          sudo apt-get update -y
          sudo apt-get -y install reprepro
          mkdir debian 
          cd debian
          
    - uses: actions/checkout@v3
      with:
        path: './debian'
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Prepare files for debian repository
      run: |
          cd ./debian
          reprepro --basedir . remove bookworm fastfetch
          reprepro --basedir . includedeb bookworm /home/runner/work/OPi5Plus-Soft/OPi5Plus-Soft/artifacts/fastfetch-stable.deb

    - name: Update git repository
      uses: EndBug/add-and-commit@v9.1.3
      with:
        cwd: './debian'
        message: 'Automatic update of the repository.'

