name: Iosevka DEB Build
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version to be built'
        default: 'v3.0.1'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  iosevka-build:
    name: Build iosevka packages
    runs-on: ubuntu-latest
    env:
      pkgversion: ${{ inputs.version }}
      fontdir: /usr/share/fonts/truetype/iosevka
      docdir: /usr/share/doc/iosevka
    steps:
    - name: Download iosevka.tar.xz
      run: |
          mkdir artifacts
          mkdir source
          cd source
          wget -q https://github.com/ryanoasis/nerd-fonts/releases/download/${{ inputs.version }}/Iosevka.tar.xz 
          tar -xf Iosevka.tar.xz
    - name: Prepare build script
      run: |
          wget -q https://raw.githubusercontent.com/foil-hat-guy/OPi5Plus-Soft/main/scripts/build-iosevka.sh
          chmod a+x ./build-iosevka.sh
        
    - name: Build IosevkaNerdFont.deb
      env:
        basename: IosevkaNerdFont
        pkgname: iosevka-nerd-font
      run: |
          ./build-iosevka.sh
          dpkg-deb --build ./$basename
          cp ./*.deb ./artifacts
          
    - name: Build IosevkaNerdFontMono.deb
      env:
        basename: IosevkaNerdFontMono
        pkgname: iosevka-nerd-font-mono
      run: |
          ./build-iosevka.sh 'Monospace version.'
          dpkg-deb --build ./$basename
          cp ./*.deb ./artifacts
    
    - name: Save DEB to cache
      uses: actions/cache/save@v3.3.1
      with:
        path: /home/runner/work/OPi5Plus-Soft/OPi5Plus-Soft/artifacts/*.deb
        key: iosevka.debs
    
  report-fail:
    name: Report build fail.
    runs-on: ubuntu-latest
    if: always() && needs.iosevka-build.result == 'failure'
    needs: iosevka-build
    steps:
    - name: Send notification
      uses: appleboy/telegram-action@v0.1.1
      with:
        token: ${{ secrets.TELEGRAMBOT }}
        to: ${{ secrets.TELEGRAMCHAT }}
        message: Warning! Iosevka build failed!

  report-ok:
    name: Report new version.
    runs-on: ubuntu-latest
    if: always() && needs.iosevka-build.result == 'success'
    needs: iosevka-build
    steps:
    - name: Send notification
      uses: appleboy/telegram-action@v0.1.1
      with:
        token: ${{ secrets.TELEGRAMBOT }}
        to: ${{ secrets.TELEGRAMCHAT }}
        message: Good News! A new version ${{ inputs.version }} of Iosevka is ready!
