name: Iosevka DEB Build
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version to be built'
        default: '3.0.1'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  iosevka-build:
    name: Build iosevka packages
    runs-on: ubuntu-latest
    env:
      pkgversion: ${{ inputs.version }}
      fontdir: /usr/share/fonts/truetype/iosevka
      docdir: /usr/share/doc/iosevka
    steps:
    - name: Download iosevka.tar.xz
      run: |
          mkdir artifacts
          mkdir source
          cd source
          wget -q https://github.com/ryanoasis/nerd-fonts/releases/download/v$pkgversion/Iosevka.tar.xz 
          tar -xf Iosevka.tar.xz
          wget -q https://github.com/ryanoasis/nerd-fonts/releases/download/v$pkgversion/IosevkaTerm.tar.xz 
          tar -xf IosevkaTerm.tar.xz
    - name: Prepare build script
      run: |
          wget -q https://raw.githubusercontent.com/foil-hat-guy/OPi5Plus-Soft/main/scripts/build-iosevka.sh
          chmod a+x ./build-iosevka.sh
        
    - name: Build IosevkaNerdFont.deb
      env:
        basename: IosevkaNerdFont
        pkgname: iosevka-nerd-font
      run: |
          ./build-iosevka.sh
          
          cat <<EOT >> ./$basename/DEBIAN/control
          Description: Iosevka nerd font.
           This package contains regular, bold, italic and bold italic fonts.
          EOT
          
          dpkg-deb --build ./$basename
          cp ./*.deb ./artifacts
          
    - name: Build IosevkaNerdFontMono.deb
      env:
        basename: IosevkaNerdFontMono
        pkgname: iosevka-nerd-font-mono
      run: |
          ./build-iosevka.sh
          
          cat <<EOT >> ./$basename/DEBIAN/control
          Description: Iosevka nerd font. Monospace variant.
           This package contains regular, bold, italic and bold italic fonts.
          EOT
          
          dpkg-deb --build ./$basename
          cp ./*.deb ./artifacts
    
    - name: Build IosevkaNerdFontPropo.deb
      env:
        basename: IosevkaNerdFontPropo
        pkgname: iosevka-nerd-font-propo
      run: |
          ./build-iosevka.sh

          cat <<EOT >> ./$basename/DEBIAN/control
          Description: Iosevka nerd font. Proportional variant.
           This package contains regular, bold, italic and bold italic fonts.
          EOT
          
          dpkg-deb --build ./$basename
          cp ./*.deb ./artifacts
    
    - name: Build IosevkaTermNerdFont.deb
      env:
        basename: IosevkaTermNerdFont
        pkgname: iosevka-term-nerd-font
      run: |
          ./build-iosevka.sh

          cat <<EOT >> ./$basename/DEBIAN/control
          Description: Iosevka Term nerd font.
           This package contains regular, bold, italic and bold italic fonts.
           This font is more suitable for terminals with restricted capabilities.
          EOT
          
          dpkg-deb --build ./$basename
          cp ./*.deb ./artifacts
          
    - name: Build IosevkaTermNerdFontMono.deb
      env:
        basename: IosevkaTermNerdFontMono
        pkgname: iosevka-term-nerd-font-mono
      run: |
          ./build-iosevka.sh
          
          cat <<EOT >> ./$basename/DEBIAN/control
          Description: Iosevka Term nerd font. Monospace variant.
           This package contains regular, bold, italic and bold italic fonts.
           This font is more suitable for terminals with restricted capabilities.
          EOT
          
          dpkg-deb --build ./$basename
          cp ./*.deb ./artifacts
    
    - name: Build IosevkaTermNerdFontPropo.deb
      env:
        basename: IosevkaTermNerdFontPropo
        pkgname: iosevka-term-nerd-font-propo
      run: |
          ./build-iosevka.sh

          cat <<EOT >> ./$basename/DEBIAN/control
          Description: Iosevka Term nerd font. Proportional variant.
           This package contains regular, bold, italic and bold italic fonts.
           This font is more suitable for terminals with restricted capabilities.
          EOT
          
          dpkg-deb --build ./$basename
          cp ./*.deb ./artifacts

    - name: Build Iosevka.deb
      run: |
          mkdir -p ./iosevka/DEBIAN
          touch ./iosevka/DEBIAN/control
          
          cat <<EOT >> ./iosevka/DEBIAN/control
          Package: $pkgname
          Maintainer: Foil-hat-guy <dev@foilhatguy.casa> 
          Priority: optional 
          Essentional: no 
          Architecture: all
          Depends: iosevka-nerd-font (= $pkgversion),
           iosevka-nerd-font-mono (= $pkgversion),
           iosevka-nerd-font-propo (= $pkgversion),
           iosevka-term-nerd-font (= $pkgversion),
           iosevka-term-nerd-font-mono (= $pkgversion),
           iosevka-term-nerd-font-propo (= $pkgversion)
          Section: fonts 
          Homepage: https://www.nerdfonts.com/ 
          Version: $pkgversion 
          Installed-Size: $(du -sk ./iosevka | cut -f 1)
          Description: It is a meta-package. It installs a set of Iosevka and IosevkaTerm nerd fonts. 
           There are default, monospace and proportional variants for both of them. Each font family 
           includes regular, bold, italic and bold italic fonts. All in all there are 24 fonts in six 
           font families.
          EOT

          dpkg-deb --build ./iosevka.deb
          cp ./*.deb ./artifacts
    
    - name: Save DEB to cache
      uses: actions/cache/save@v3.3.1
      with:
        path: /home/runner/work/OPi5Plus-Soft/OPi5Plus-Soft/artifacts/*.deb
        key: iosevka.debs
    
  report-fail:
    name: Report build fail.
    runs-on: ubuntu-latest
    if: always() && needs.iosevka-build.result == 'failure'
    needs: iosevka-build
    steps:
    - name: Send notification
      uses: appleboy/telegram-action@v0.1.1
      with:
        token: ${{ secrets.TELEGRAMBOT }}
        to: ${{ secrets.TELEGRAMCHAT }}
        message: Warning! Iosevka build failed!

  report-ok:
    name: Report new version.
    runs-on: ubuntu-latest
    if: always() && needs.iosevka-build.result == 'success'
    needs: iosevka-build
    steps:
    - name: Send notification
      uses: appleboy/telegram-action@v0.1.1
      with:
        token: ${{ secrets.TELEGRAMBOT }}
        to: ${{ secrets.TELEGRAMCHAT }}
        message: Good News! A new version ${{ inputs.version }} of Iosevka is ready!
