name: Get Fastfetch DEB
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version to be built'
        default: '1.12.1'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  fastfetch-aarch64-build:
    name: Get fastfetch for arm64 architecture
    runs-on: ubuntu-latest
    steps:
    
    - name: Download fastfetch.deb
      run: |
            mkdir artifacts
            cd ./artifacts
            wget -O fastfetch.deb https://github.com/fastfetch-cli/fastfetch/releases/download/${{ inputs.version }}/fastfetch-linux-aarch64.deb
            git clone --branch ${{ inputs.version }} --depth 1 'https://github.com/fastfetch-cli/fastfetch.git'
            echo '====================='
            ls
    
    - name: Save DEB to cache
      uses: actions/cache/save@v4
      with:
        path: /home/runner/work/OPi5Plus-Soft/OPi5Plus-Soft/artifacts/fastfetch.deb
        key: fastfetch.deb
    
  report-fail:
    name: Report build fail.
    runs-on: ubuntu-latest
    if: always() && needs.fastfetch-aarch64-build.result == 'failure'
    needs: fastfetch-aarch64-build
    steps:
    - name: Send notification
      uses: appleboy/telegram-action@v0.1.1
      with:
        token: ${{ secrets.TELEGRAMBOT }}
        to: ${{ secrets.TELEGRAMCHAT }}
        message: Warning! FastFetch build failed!

  report-ok:
    name: Report new version.
    runs-on: ubuntu-latest
    if: always() && needs.fastfetch-aarch64-build.result == 'success'
    needs: fastfetch-aarch64-build
    steps:
    - name: Send notification
      uses: appleboy/telegram-action@v0.1.1
      with:
        token: ${{ secrets.TELEGRAMBOT }}
        to: ${{ secrets.TELEGRAMCHAT }}
        message: Good News! A new version ${{ inputs.version }} of FastFetch is ready!
